services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SMTP_USER
        value: diegoespinoza1405@gmail.com
      - key: SMTP_PASS
        value: aqstidposhvhsrbd
      - key: TO_EMAIL
        value: diegoespinoza1405@gmail.com
    healthCheckPath: /api/health